CREATE TABLE IF NOT EXISTS `v_tuner_base` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `fMass` varchar(50) DEFAULT NULL,
  `fInitialDragCoeff` varchar(50) DEFAULT NULL,
  `fDownforceModifier` varchar(50) DEFAULT NULL,
  `fPercentSubmerged` varchar(50) DEFAULT NULL,
  `vecCentreOfMassOffset` varchar(50) DEFAULT NULL,
  `vecInertiaMultiplier` varchar(50) DEFAULT NULL,
  `fDriveBiasFront` varchar(50) DEFAULT NULL,
  `nInitialDriveGears` varchar(50) DEFAULT NULL,
  `fInitialDriveForce` varchar(50) DEFAULT NULL,
  `fDriveInertia` varchar(50) DEFAULT NULL,
  `fClutchChangeRateScaleUpShift` varchar(50) DEFAULT NULL,
  `fClutchChangeRateScaleDownShift` varchar(50) DEFAULT NULL,
  `fInitialDriveMaxFlatVel` varchar(50) DEFAULT NULL,
  `fBrakeForce` varchar(50) DEFAULT NULL,
  `fBrakeBiasFront` varchar(50) DEFAULT NULL,
  `fHandBrakeForce` varchar(50) DEFAULT NULL,
  `fSteeringLock` varchar(50) DEFAULT NULL,
  `fTractionCurveMax` varchar(50) DEFAULT NULL,
  `fTractionCurveMin` varchar(50) DEFAULT NULL,
  `fTractionCurveLateral` varchar(50) DEFAULT NULL,
  `fTractionSpringDeltaMax` varchar(50) DEFAULT NULL,
  `fLowSpeedTractionLossMult` varchar(50) DEFAULT NULL,
  `fCamberStiffnesss` varchar(50) DEFAULT NULL,
  `fTractionBiasFront` varchar(50) DEFAULT NULL,
  `fTractionLossMult` varchar(50) DEFAULT NULL,
  `fSuspensionForce` varchar(50) DEFAULT NULL,
  `fSuspensionCompDamp` varchar(50) DEFAULT NULL,
  `fSuspensionReboundDamp` varchar(50) DEFAULT NULL,
  `fSuspensionUpperLimit` varchar(50) DEFAULT NULL,
  `fSuspensionLowerLimit` varchar(50) DEFAULT NULL,
  `fSuspensionRaise` varchar(50) DEFAULT NULL,
  `fSuspensionBiasFront` varchar(50) DEFAULT NULL,
  `fAntiRollBarForce` varchar(50) DEFAULT NULL,
  `fAntiRollBarBiasFront` varchar(50) DEFAULT NULL,
  `fRollCentreHeightFront` varchar(50) DEFAULT NULL,
  `fRollCentreHeightRear` varchar(50) DEFAULT NULL,
  `fCollisionDamageMult` varchar(50) DEFAULT NULL,
  `fWeaponDamageMult` varchar(50) DEFAULT NULL,
  `fDeformationDamageMult` varchar(50) DEFAULT NULL,
  `fEngineDamageMult` varchar(50) DEFAULT NULL,
  `fPetrolTankVolume` varchar(50) DEFAULT NULL,
  `fOilVolume` varchar(50) DEFAULT NULL,
  `fSeatOffsetDistX` varchar(50) DEFAULT NULL,
  `fSeatOffsetDistY` varchar(50) DEFAULT NULL,
  `fSeatOffsetDistZ` varchar(50) DEFAULT NULL,
  `nMonetaryValue` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `name` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;